### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by rickschmoo** [marcysutton/js-a11y-workshop#5]
Heads up that I ran into this npm install issue (although on Mac):
https://github.com/gatsbyjs/gatsby/issues/11026

Fixed by installing sharp first:
```
rm -rf node_modules
rm package-lock.json
npm install sharp
npm install
```

**Comment by rickschmoo** [comment]
Apols - closing this. Issue was due to node version. LTS (14.5.4) has some memory issues w wasm on Apple M1 silicon. 15.5.1 is fine. Thats the fix if anyone else encounters this. Stay well and thanks for providing the class.

**Comment by marcysutton** [comment]
Thanks for the info, as it may help someone in the future! Glad the workshop was useful.
